[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Demir Catovic <d.catovic9@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.2"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
flake8 = "^6.0.0"
pytest = "^7.2.1"

[tool.poetry.extras]
test = [pytest]
lint = [flake8]
format = [black]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
