site_name: Addition Docs

theme:
  name: "material"

docs_dir: './docs' # default

plugins:
  - mkdocstrings

nav:
  - index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md
