name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        python -m pipx ensurepath
        pipx install poetry
        pipx install nox 
    - name: Testing
      run: nox --session test
    - name: Linting
      run: nox --session lint
    - name: Formatting
      run: nox --session format
    - name: Static Type Check
      run: nox --session static_type_check
    

