name: Coverage Reporting
on: push
jobs:
  coverage:
    runs-on: [ubuntu-22.04]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip==22.3.1
        python3 -m pip install --user pipx==1.1.0
        python3 -m pipx ensurepath
        pipx install poetry==1.3.2
        pipx install nox==2022.11.21
    - run: nox --sessions upload_coverage_report --force-color
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}